# Generated by Django 4.2.4 on 2023-08-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'admin'), ('CUSTOMER', 'customer'), ('PROVIDER', 'provider')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('loan_interest', models.FloatField()),
                ('loan_tenure', models.IntegerField()),
                ('loan_emi', models.FloatField()),
                ('loan_status', models.CharField(max_length=50)),
                ('loan_created', models.DateTimeField(auto_now_add=True)),
                ('loan_updated', models.DateTimeField(auto_now=True)),
                ('loan_is_approved', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.user')),
            ],
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=50)),
                ('fund_amount', models.IntegerField()),
                ('fund_created', models.DateTimeField(auto_now_add=True)),
                ('fund_updated', models.DateTimeField(auto_now=True)),
                ('fund_is_approved', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.user')),
            ],
        ),
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('amortization_id', models.AutoField(primary_key=True, serialize=False)),
                ('amortization_month', models.IntegerField()),
                ('amortization_principal', models.FloatField()),
                ('amortization_interest', models.FloatField()),
                ('amortization_emi', models.FloatField()),
                ('amortization_balance', models.FloatField()),
                ('amortization_created', models.DateTimeField(auto_now_add=True)),
                ('amortization_updated', models.DateTimeField(auto_now=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
        ),
    ]
