# Generated by Django 4.2.4 on 2023-08-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funds',
            new_name='Fund',
        ),
    ]
