# Generated by Django 4.2.4 on 2023-08-10 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0005_alter_fund_user_id_alter_loan_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance', models.IntegerField()),
                ('bank_min_loan', models.IntegerField()),
                ('bank_max_loan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FundApplication',
            fields=[
                ('fund_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_application_created', models.DateTimeField(auto_now_add=True)),
                ('fund_application_updated', models.DateTimeField(auto_now=True)),
                ('fund_application_status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], max_length=50)),
                ('fund_ammount', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_updated', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('LOAN', 'loan'), ('FUND', 'fund'), ('INSTALLMENTS', 'installments')], max_length=50)),
                ('transaction_ammount', models.IntegerField()),
                ('transaction_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_application_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_application_is_approved',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_application_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default=loans.models.ApplicationStatus['PENDING'], max_length=50),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
