# Generated by Django 4.2.4 on 2023-08-11 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0007_rename_transactions_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_created', models.DateTimeField(auto_now_add=True)),
                ('loan_updated', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.IntegerField()),
                ('loan_tenure', models.IntegerField()),
                ('loan_interest', models.FloatField()),
                ('loan_status', models.CharField(choices=[('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], default='ongoing', max_length=50)),
                ('loan_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Amortization',
        ),
        migrations.RenameField(
            model_name='fundapplication',
            old_name='fund_ammount',
            new_name='fund_amount',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='loan_ammount',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_ammount',
            new_name='transaction_amount',
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='fund_application_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_application_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='pending', max_length=50),
        ),
    ]
