# Generated by Django 4.2.4 on 2023-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loan_delete_amortization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_min_loan', models.IntegerField()),
                ('bank_max_loan', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bankbalance',
            name='bank_max_loan',
        ),
        migrations.RemoveField(
            model_name='bankbalance',
            name='bank_min_loan',
        ),
    ]
